In [ ]:
import numpy as np

In [4]:
N = 10

r = np.zeros(N)
# r = np.full(10, 7.8)
print(r)

for i in range(N):
    r[i] = i ** 2
    
print(r)

del r

r = np.zeros((4, 5))
print(r)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
# Exercise: Compare three methods of creating an array
# N = 10000
# r[i] = i**"
# time test!

import time

N = 10000

c = time.perf_counter()
first = np.zeros(N)
for i in range(N): first[i] = i ** 2
print('Duration first: ' + str(time.perf_counter() - c))

c = time.perf_counter()
second = []
for i in range(N): second.append(i ** 2)
print('Duration second: ' + str(time.perf_counter() - c))

c = time.perf_counter()
third = np.array([])
for i in range(N): np.append(third, i ** 2)
print('Duration third: ' + str(time.perf_counter() - c))

Duration first: 0.007637660000000324
Duration second: 0.0018405990003884654
Duration third: 0.03731574199991883
