In [ ]:
import numpy as np

In [ ]:
x = np.array([ [1,2,3],
               [2,3,4],
               [3,4,5],
               [4,5,6] ])

w = np.array([10,20,30])

print(x)
print()
print(w)

In [ ]:
y = np.zeros(x.shape)

for i in range(x.shape[0]):
    y[i,:] = x[i,:] + w

y

In [ ]:
# broadcasting
z = x + w

print(z)
print()
print(y)

In [ ]:
v = np.array([-1,0,1,0], ndmin=2).T
# v = np.array([[-1],[0],[1],[0]])
print(x)
print(v)
x*v

In [31]:
# Exercise:
# 1) create a vector of integers from 0 to 8 (v)
# 2) reshape v into a three by three matrix (M) (np.reshape)
# 3) repeat M into a 9x3 (C) (np.tile)
# 4) broadcast-multiply C with v (B)
v = np.array([0,1,2,3,4,5,6,7,8])
print(v)
print()
M = np.reshape(v, (3,3))
print(M)
print()
C = np.tile(M, (3,1))
print(C)
print()

B = C * np.array(v, ndmin=2).T
B

[0 1 2 3 4 5 6 7 8]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]



array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [ 0,  3,  6],
       [12, 16, 20],
       [30, 35, 40],
       [ 0,  6, 12],
       [21, 28, 35],
       [48, 56, 64]])