In [19]:
import numpy as np
# from numpy import mean as m

numbers = [ 1, 2, 3, 4, 5 ]

np.mean(numbers)

np.float64(3.0)

In [20]:
x = np.linspace(1, 7, 5)
print(x)
type(x)

[1.  2.5 4.  5.5 7. ]


numpy.ndarray

In [21]:
numbers_np = np.array(numbers)

print(type(numbers))
print(type(numbers_np))

<class 'list'>
<class 'numpy.ndarray'>


In [22]:
np.max(numbers)

np.int64(5)

In [23]:
# in place

n = [ 4, 3, 5, 2, 6, 1, 7 ]
nn = np.array(n)

print(nn)
nn.sort()
print(nn)

[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]


In [24]:
# out of place
n = [ 4, 3, 5, 2, 6, 1, 7 ]
nn = np.array(n)
print(nn)
nns = np.sort(nn)
print(nns)
print(nn)

[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]
[4 3 5 2 6 1 7]
