In [18]:
import numpy as np
from numpy import mean

In [9]:
numbers = [1, 2, 3, 4, 5]

print(np.mean(numbers))

x = np.linspace(1, 7, 5) # Output is not a list, but a numpy array
print(x)
print(type(x))

3.0
[1.  2.5 4.  5.5 7. ]
<class 'numpy.ndarray'>


In [11]:
numbers_np = np.array(numbers)
print(type(numbers))
print(type(numbers_np))

<class 'list'>
<class 'numpy.ndarray'>


In [16]:
print(numbers_np.mean())
print(numbers_np.max())
print(np.max(numbers_np))


3.0
5
5


In [20]:
print(mean(numbers_np)) # Only works with "from numpy import mean"

3.0


In [24]:
# in-place vs out-of-place/not in-place operations
n = [ 4, 3, 5, 2, 6, 1, 7 ]

# in-place: n.sort()
nn = np.array(n)
nn.sort()
print(nn) # also inline

nn = np.array(n)
print(np.sort(nn))
print(nn) # array itself unchanged

nns = np.sort(nn)
print(nns)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]
