In [1]:
# class: blueprint for creating a set of attributes and methods
# instance

In [19]:
class model(object):
    # constructor method
    def __init__(self, numlayers, numunits, name):
        self.layers = numlayers # attribute
        self.units = numunits
        self.name = name
        self.weights = 1

    def howManyUnits(self):
        totalUnits = self.layers * self.units
        print(f'There are {totalUnits} units in the model')

    def trainTheModel(self, x):
        self.weights += x
        return self.weights

    def __str__(self):
        return f'This is a {self.name} architecture'

In [22]:
m1 = model(12, 5, 'CNN')
m1.howManyUnits()
print(m1.trainTheModel(2.5))
print(m1.trainTheModel(1))

str(m1)


There are 60 units in the model
3.5
4.5


'This is a CNN architecture'

In [26]:
# Exercise: Create a new class
# 1) weights should be a random numbers matrix of size layers X units
# 2) change the training method to multiply X and add input Y
import numpy as np
np.random.randn(10, 2)

array([[-0.09146675,  0.22671193],
       [-0.46020691,  1.41696396],
       [ 1.14400662,  0.01518338],
       [ 0.12349573,  0.23937924],
       [ 1.25177641,  0.13138245],
       [ 0.05251654,  0.22038161],
       [-0.06361233, -0.19939757],
       [ 0.74050806,  0.48761731],
       [ 0.12434698, -1.20459874],
       [-0.91779807,  0.49405273]])

In [28]:


class MyModel(object):
    # constructor method
    def __init__(self, numlayers, numunits, name):
        self.layers = numlayers # attribute
        self.units = numunits
        self.name = name
        self.weights = np.random.randn(numlayers, numunits)

    def how_many_units(self):
        total_units = self.layers * self.units
        print(f'There are {total_units} units in the model')

    def train_the_model(self, x, y):
        self.weights = self.weights * x + y
        return self.weights

    def __str__(self):
        return f'This is a {self.name} architecture'

In [32]:
m2 = MyModel(2, 3, 'myModel')
str(m2)
print(m2.weights)
m2.train_the_model(1.5, 3)


[[-0.71089855 -1.69841121  1.19634586]
 [-1.828276    0.21098377  0.53612772]]


array([[1.93365217, 0.45238318, 4.79451879],
       [0.25758599, 3.31647565, 3.80419158]])

In [36]:
print(m2.weights)
m2.train_the_model(1.5, 3)

[[20.77607609 15.77679324 30.43150092]
 [15.11935273 25.44310533 27.08914659]]


array([[34.16411413, 26.66518987, 48.64725138],
       [25.67902909, 41.16465799, 43.63371988]])