In [4]:
# initializing
import numpy as np

In [8]:
r = np.zeros(10)

for i in range(10):
    r[i] = i**2

print(r)


N = 12
r = np.full(N, 0)

for i in range(N):
    r[i] = i**2

print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
[  0   1   4   9  16  25  36  49  64  81 100 121]


In [12]:
r = []
del r
# print(r) # fails, because r removed

# init n-dim matrix
r = np.zeros((4, 5))
print(r)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
r = np.array([])

for i in range(10):
    r = np.append(r, i**2) # append is immutable operation

print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [23]:
# Exercise: compare three methods of creating an array
# N = 10_000
# r[i] = i ** 2
# time test: import time -> time.perf_counter()
import time

N = 100_000

start = time.perf_counter()
r = []
for i in range(N):
    r.append(i ** 2)
print('Time elapsed: ' + str(time.perf_counter() - start))

start = time.perf_counter()
r = np.array([])
for i in range(N):
    r = np.append(r, i ** 2)
print('Time elapsed: ' + str(time.perf_counter() - start))

start = time.perf_counter()
r = np.zeros(N)
for i in range(N):
    r[i] = i ** 2
print('Time elapsed: ' + str(time.perf_counter() - start))

Time elapsed: 0.03842150699983904
Time elapsed: 1.9937938549996943
Time elapsed: 0.027693485999861878
