In [4]:
import numpy as np

X = np.array([ [1, 2, 3],
               [2, 3, 4],
               [3, 4, 5],
               [4, 5, 6] ])

w = np.array([ 10, 20, 30 ])

print(X)
print()
print(w)
print()

for i in range(X.shape[0]):
    X[i,:] = X[i,:] + w

print(X)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]

[10 20 30]

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]


In [9]:
X = np.array([ [1, 2, 3],
               [2, 3, 4],
               [3, 4, 5],
               [4, 5, 6] ])

w = np.array([ 10, 20, 30 ])

Y = np.zeros(X.shape)

for i in range(X.shape[0]):
    Y[i,:] = X[i,:] + w

In [20]:
X = np.array([ [1, 2, 3],
               [2, 3, 4],
               [3, 4, 5],
               [4, 5, 6] ])

w = np.array([ [ 10, 20, 30 ] ])
v = np.array([ [ 10, 20, 30, 40 ] ]).T

# broadcasting
# Mathematically illegal operation
Y = X + w
Z = X + v

print(w)
print()
print(Y)
print()
print(Z)
print()

[[10 20 30]]

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]

[[11 12 13]
 [22 23 24]
 [33 34 35]
 [44 45 46]]



In [31]:
# Exercise:
# 1) create vector of integers 0:8 (v)
# 2) reshape v into 3X3 matrix (M) (np.reshape)
# 3) repeat M into a 9 X 3 (C) (np.tile)
# 4) broadcast-multiply C with v (B)

v = np.array(range(9), ndmin=2)
M = np.reshape(v, (3, 3))
C = np.tile(M, (3, 1))
B = C * v.T
B

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [ 0,  3,  6],
       [12, 16, 20],
       [30, 35, 40],
       [ 0,  6, 12],
       [21, 28, 35],
       [48, 56, 64]])